# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fluxograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TarefaFluxograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('fluxograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxograma.Fluxograma')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxograma.Tarefa')),
            ],
            options={
                'ordering': ('numero',),
            },
        ),
        migrations.AddField(
            model_name='fluxograma',
            name='tarefas',
            field=models.ManyToManyField(through='fluxograma.TarefaFluxograma', to='fluxograma.Tarefa'),
        ),
        migrations.AlterUniqueTogether(
            name='tarefafluxograma',
            unique_together=set([('tarefa', 'fluxograma', 'numero')]),
        ),
    ]
